// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABg85UIe5YB-FR87IdVpOKNlpYsn5TPqM',
    appId: '1:1054233603062:web:0b2419ef63f62a49a575d7',
    messagingSenderId: '1054233603062',
    projectId: 'make-it-happen-4c514',
    authDomain: 'make-it-happen-4c514.firebaseapp.com',
    storageBucket: 'make-it-happen-4c514.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsa9XZyLYRtLcTdntGbsrwOXiZM4ASugQ',
    appId: '1:1054233603062:android:425890c191cc8e76a575d7',
    messagingSenderId: '1054233603062',
    projectId: 'make-it-happen-4c514',
    storageBucket: 'make-it-happen-4c514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXQyBuS2NeiscwGoafsgtzlSiyWLA4Mo',
    appId: '1:1054233603062:ios:a0147d0514a6ce3ca575d7',
    messagingSenderId: '1054233603062',
    projectId: 'make-it-happen-4c514',
    storageBucket: 'make-it-happen-4c514.firebasestorage.app',
    iosBundleId: 'com.example.makeItHappen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVXQyBuS2NeiscwGoafsgtzlSiyWLA4Mo',
    appId: '1:1054233603062:ios:a0147d0514a6ce3ca575d7',
    messagingSenderId: '1054233603062',
    projectId: 'make-it-happen-4c514',
    storageBucket: 'make-it-happen-4c514.firebasestorage.app',
    iosBundleId: 'com.example.makeItHappen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABg85UIe5YB-FR87IdVpOKNlpYsn5TPqM',
    appId: '1:1054233603062:web:a8b723f47ac26ef9a575d7',
    messagingSenderId: '1054233603062',
    projectId: 'make-it-happen-4c514',
    authDomain: 'make-it-happen-4c514.firebaseapp.com',
    storageBucket: 'make-it-happen-4c514.firebasestorage.app',
  );
}
